package com.anurag.stocks;

import java.util.*;

import org.apache.http.client.params.AllClientPNames;

public class Symbols {


  static String selectedTopSheet = "AARTIDRUGS,AARTIIND,AAVAS,ABB,POWERINDIA,ABBOTINDIA,ADANIENT,ADANIGAS,ADANIGREEN,ADANIPORTS," +
          "ADANITRANS,ABFRL,ADVENZYMES,AEGISCHEM,AIAENG,APLLTD,ALKYLAMINE,AMARAJABAT,AMBER,AMBUJACEM,ANGELBRKG,APARINDS," +
          "APLAPOLLO,APOLLOHOSP,APOLLOTYRE,ASAHIINDIA,ASIANPAINT,ASTEC,ASTERDM,ASTRAL,ASTRAZEN,ATUL,AUBANK,AUROPHARMA,DMART," +
          "AXISBANK,BAJAJ-AUTO,BAJFINANCE,JSLHISAR,BAJAJFINSV,BAJAJHLDNG,BALKRISIND,BALRAMCHIN,BASF,BATAINDIA,BAYERCROP,BERGEPAINT," +
          "BDL,BHARATFORG,BPCL,BHARATRAS,BHARTIARTL,BIOCON,BSOFT,BLISSGVS,BLUESTARCO,BBTC,BRIGADE,BRITANNIA,BURGERKING," +
          "CADILAHC,CANFINHOME,CAPLIPOINT,CGCL,CARBORUNIV,CCL,CDSL,CENTURYPLY,CERA,CESC,CHAMBLFERT,CHEMCON,CHOLAHLDNG," +
          "CHOLAFIN,CIPLA,CUB,COCHINSHIP,COFORGE,COLPAL,CAMS,CONCOR,COROMANDEL,CREDITACC,CRISIL,CROMPTON,CSBBANK,CYIENT," +
          "DABUR,DALBHARAT,DCMSHRIRAM,DEEPAKNTR,DIVISLAB,DIXON,LALPATHLAB,DRREDDY,EIDPARRY,EICHERMOT,ELGIEQUIP,EMAMILTD," +
          "EPL,EQUITASBNK,ERIS,ESABINDIA,ESCORTS,EXIDEIND,FDC,FINEORG,FINPIPE,FSL,FORTIS,GAIL,GALAXYSURF,GARFIBRES,GHCL," +
          "GILLETTE,GLAND,GLAXO,GODFRYPHLP,GODREJAGRO,GODREJCP,GODREJIND,GODREJPROP,GRANULES,GRASIM,GRINDWELL,GUJGASLTD," +
          "GSPL,GULFOILLUB,HAPPSTMNDS,HATSUN,HAVELLS,HCLTECH,HDFCAMC,HDFCLIFE,HEIDELBERG,HEROMOTOCO,HESTERBIO,HFCL,HINDALCO," +
          "HAL,HINDUNILVR,HINDZINC,HONAUT,HDFC,ICICIGI,ICICIPRULI,ISEC,IFBIND,INDIACEM,INDIAMART,IEX,INDHOTEL,IRCTC,IGL,NAUKRI," +
          "INFY,INTELLECT,INDIGO,IOLCP,IPCALAB,ITI,JBCHEPHARM,JKCEMENT,JKCEMENT,JAMNAAUTO,JSL,JKLAKSHMI,JKPAPER,JCHAC,JSWSTEEL," +
          "JUBLFOOD,JUBILANT,JYOTHYLAB,KAJARIACER,KALPATPOWR,KANSAINER,KEC,KEI,KENNAMET,KNRCON,KOLTEPATIL,KOTAKBANK,KPRMILL," +
          "LTTS,LAOPALA,LTI,LT,GMMPFAUDLR,LAURUSLABS,LUMAXIND,LUXIND,MGL,MAHSCOOTER,MAHSEAMLES,M&M,MAHLOG,MAITHANALL," +
          "MANAPPURAM,MARICO,MASFIN,MASTEK,MFSL,MAZDOCK,METROPOLIS,MINDAIND,MINDTREE,MOTHERSUMI,MPHASIS,MRF,INOXLEISUR,MCX," +
          "MUTHOOTFIN,NH,NHPC,NATCOPHARM,NAVINFLUOR,NEOGEN,NESCO,NESTLEIND,NILKAMAL,NOCIL,OBEROIRLTY,OFSS,ORIENTELEC,ORIENTREF," +
          "PIIND,PAGEIND,PERSISTENT,PETRONET,PRSMJOHNSN,PHOENIXLTD,PNCINFRA,POKARNA,POLYMED,POLYCAB,POLYPLEX,PFC,POWERGRID,PRAJIND," +
          "PRESTIGE,PRINCEPIPE,PGHL,PGHH,PSPPROJECT,PVR,RADICO,RVNL,RAMCOCEM,RATNAMANI,REDINGTON,RELAXO,RELIANCE,RESPONIND,RITES," +
          "ROSSARI,ROUTE,SANOFI,SBICARD,SBILIFE,SCHAEFFLER,SEQUENT,SFL,SHILPAMED,SHREECEM,SRTRANSFIN,SIEMENS,SJVN,SOBHA," +
          "SOLARINDS,SPICEJET,SRF,STARCEMENT,SBIN,STAR,SUDARSCHEM,SUMICHEM,SUNDARMFIN,GESHIP,SUNDRMFAST,SUNTECK,SUPRAJIT," +
          "SUPREMEIND,SUPPETRO,SUVENPHAR,SWANENERGY,SWARAJENG,SYNGENE,TASTYBITE,TATACHEM,TCS,TATACONSUM,TATAELXSI,TATAINVEST," +
          "TATASTEEL,TCIEXP,TEAMLEASE,TECHM,THERMAX,THYROCARE,TIMKEN,TITAN,TORNTPHARM,TORNTPOWER,TRENT,TIINDIA,TVSMOTOR,UFLEX," +
          "ULTRACEMCO,UBL,MCDOWELL-N,UPL,UTIAMC,VIPIND,VMART,VAIBHAVGBL,VTL,VBL,VINATIORGA,VOLTAS,VSTIND,WABCOINDIA,WELCORP," +
          "WELSPUNIND,WESTLIFE,WHIRLPOOL,WIPRO,CEATLTD,ZENSARTECH,ZYDUSWELL,GRSE,ICRA,KPITTECH,MIDHANI,SONATSOFTW,IRCON,SOLARA," +
          "ICICIBANK,RALLIS,SIS,UJJIVANSFB,BAJAJELEC,TTKPRESTIG,VGUARD,BIRLACORPN,SKFINDIA,AFFLE,AKZOINDIA,HDFCBANK,AJANTPHARM," +
          "INDOSTAR,ENDURANCE,NAM-INDIA,3MINDIA,FEDERALBNK,PFIZER,RECLTD,ASHOKLEY,BEL,ACC,ALKEM,PIDILITIND,MARUTI";


  static String badList = "ZUARI,TEXINFRA,MARATHON,ZUARIGLOB,STCINDIA,HINDCOPPER,ONWARDTEC,KOTAKPSUBK,NETFCONSUM,ITDC,ARROWGREEN,PFOCUS," +
          "KESORAMIND,HERCULES,GANGESSECU,PANACEABIO,KHADIM,ELECTHERM,VAKRANGEE,KAKATCEM,TBZ,MANGCHEFER,SWELECTES,HITECH,NAHARCAP," +
          "TTL,TWL,GEECEE,SILINV,KIOCL,GILLANDERS,WEIZMANIND,ICICIMCAP,KREBSBIO,UFO,EMAMIREAL,SHREYAS,MUKANDLTD,RUBYMILLS,DVL,KANORICHEM," +
          "RANEENGINE,CAPTRUST,SANGAMIND,TREJHARA,SORILINFRA,KAMDHENU,INDOTECH,PAISALO,EMKAY,SPECIALITY,EMAMIPAP,EKC,SNOWMAN,XELPMOC,MAN50ETF," +
          "BRNL,ZODIACLOTH,VAISHALI,KABRAEXTRU,STEL,IDFC,AROGRANITE,VLSFINANCE,IMFA,INDSWFTLAB,JAYAGROGN,GMDCLTD,MAXVIL,SCHNEIDER,CINELINE,HUDCO," +
          "SSWL,TOKYOPLAST,ADSL,SHALBY,ICICINV20,TALBROAUTO,CAREERP,PRICOLLTD,MMP,PIONDIST,INEOSSTYRO,TEXRAIL,UNICHEMLAB,ISFT,KELLTONTEC,PANACHE.NS," +
          "GSCLCEMENT,UNIENTER,FACT,";

  String sym =
      "AMBUJACEM,ASIANPAINT,AUROPHARMA,AXISBANK,BAJFINANCE,BHARTIARTL,BPCL,CIPLA,COALINDIA,DRREDDY,"
          + "GAIL,HCLTECH,HDFC,HDFCBANK,HEROMOTOCO,HINDALCO,HINDPETRO,HINDUNILVR,IBULHSGFIN,ICICIBANK,INDUSINDBK,INFRATEL,"
          + "INFY,IOC,ITC,KOTAKBANK,LT,LUPIN,M&M,MARUTI,NTPC,ONGC,POWERGRID,RELIANCE,SBIN,SUNPHARMA,"
          + "TATAMOTORS,TCS,TECHM,ULTRACEMCO,UPL,WIPRO,YESBANK,ZEEL," +

          "ABB,ACC,ASHOKLEY,BAJAJFINSV,BEL,BHEL,BRITANNIA,BAJAJ-AUTO,CADILAHC,COLPAL,CONCOR,CUMMINSIND,DABUR,DLF,"
          + "DMART,EMAMILTD,GLAXO,GLENMARK,GODREJCP,HAVELLS,ICICIPRULI,IDEA,INDIGO,JSWSTEEL,"
          + "LICHSGFIN,MARICO,MOTHERSUMI,OIL,PEL,PETRONET,PFC,PGHH,PIDILITIND,PNB,"
          + "SAIL,SHREECEM,SRTRANSFIN,SUNTV,TITAN,TORNTPHARM," +

          "AMARAJABAT,APOLLOTYRE,ARVIND,BERGEPAINT,"
          + "BIOCON,CASTROLIND,CENTURYTEX,DISHTV,DIVISLAB,ENGINERSIN,EXIDEIND,FEDERALBNK,GMRINFRA,"
          + "GODREJIND,IDFC,IDFCBANK,IGL,L&TFH,M&MFIN,MINDTREE,MUTHOOTFIN,"
          + "RBLBANK,STAR,TATACHEM,TATAGLOBAL,TVSMOTOR,UBL," +

          "KSCL,COROMANDEL,VSTTILLERS,ASHIANA,PIIND,AJANTPHARM,DIVISLAB,ALLCARGO,CERA,ICICIPRULI,HDFCLIFE,KAJARIACER,VOLTAS,ESCORTS,MFSL,TTKPRESTIG,VIPIND,ASTRAL,PAGEIND,ABCAPITAL,DHFL,GRUH,EVERESTIND,CANFINHOME";

  String temp = "AMBUJACEM,ASIANPAINT,AUROPHARMA,AXISBANK,BAJFINANCE,BHARTIARTL";

  static String t = "UNIPLY,TTKHLTCARE,QGOLDHALF,TIFIN,TASTYBITE,RSYSTEMS,RELDIVOPP,PDPL,PALREDTEC,MOLDTKPAC,MOLDTECH,LAKSHMIEFL,JAYSREETEA,IFGLEXPOR,HISARMETAL,FILATEX,DFMFOODS,DCAL,CONCOR,COMPINFO,CMICABLES,";

  String holdings =
      "AJANTPHARM,ALLCARGO,ASHIANA,BAJAJ-AUTO,BAJAJFINSV,BEL,BERGEPAINT,DHFL,DISHTV,EXIDEIND,HAVELLS,HDFCBANK,HDFCLIFE,ICICIPRULI,INDIGO,ITC,KSCL,LICHSGFIN,LT,MARICO,MOTHERSUMI,PIIND,RBLBANK,SBIN,TATAMOTORS,VOLTAS";

  static String nse500 =
      "3MINDIA,8KMILES,ABB,ACC,AIAENG,APLAPOLLO,AUBANK,AARTIIND,ABAN,ADANIPORTS,ADANIPOWER,ADANITRANS,"
          + "ABCAPITAL,ABFRL,ADVENZYMES,AEGISCHEM,AJANTPHARM,AKZOINDIA,APLLTD,ALKEM,ALBK,ALLCARGO,AMARAJABAT,AMBUJACEM,"
          + "ANDHRABANK,APOLLOHOSP,APOLLOTYRE,ARVIND,ASAHIINDIA,ASHOKLEY,ASHOKA,ASIANPAINT,ASTRAL,ATUL,AUROPHARMA,AVANTIFEED,"
          + "DMART,AXISBANK,BASF,BEML,BFUTILITIE,BGRENERGY,BSE,BAJAJ-AUTO,BAJAJCORP,BAJAJELEC,BAJFINANCE,BAJAJFINSV,BAJAJHIND,"
          + "BAJAJHLDNG,BALKRISIND,BALLARPUR,BALMLAWRIE,BALRAMCHIN,BANKBARODA,BANKINDIA,BATAINDIA,BERGEPAINT,BEL,BHARATFIN,BHARATFORG,"
          + "BHEL,BPCL,BHARTIARTL,INFRATEL,BHUSANSTL,BIOCON,BIRLACORPN,BLISSGVS,BLUEDART,BLUESTARCO,BBTC,BOMDYEING,BOSCHLTD,BRIGADE,"
          + "BRITANNIA,CARERATING,CCL,CGPOWER,CRISIL,CADILAHC,CANFINHOME,CANBK,CAPF,CAPLIPOINT,CARBORUNIV,CASTROLIND,CEATLTD,CENTRALBK,CDSL,"
          + "CENTURYPLY,CENTURYTEX,CERA,CHAMBLFERT,CHENNPETRO,CHOLAFIN,CIPLA,CUB,COALINDIA,COCHINSHIP,COFFEEDAY,COLPAL,CONCOR,COROMANDEL,COX&KINGS,"
          + "CROMPTON,CUMMINSIND,CYIENT,DBREALTY,DBCORP,DCBBANK,DCMSHRIRAM,DLF,DABUR,DEEPAKFERT,DELTACORP,DEN,DENABANK,DHFL,DBL,DISHTV,DCAL,DIVISLAB,"
          + "DIXON,LALPATHLAB,DRREDDY,DREDGECORP,EIDPARRY,EIHOTEL,EDELWEISS,EICHERMOT,EMAMILTD,ENDURANCE,ENGINERSIN,EQUITAS,ERIS,EROSMEDIA,ESCORTS,EVEREADY,"
          + "EXIDEIND,FEDERALBNK,FINCABLES,FINPIPE,FSL,FCONSUMER,FLFL,GAIL,GEPIL,GET&D,GHCL,GMRINFRA,GVKPIL,GDL,GATI,GICRE,GILLETTE,GSKCONS,GLAXO,GLENMARK,GODFRYPHLP,"
          + "GODREJAGRO,GODREJCP,GODREJIND,GODREJPROP,GRANULES,GRAPHITE,GRASIM,GESHIP,GREAVESCOT,GREENPLY,GRUH,GUJALKALI,GUJFLUORO,GUJGASLTD,GMDCLTD,GNFC,GPPL,GSFC,GSPL,"
          + "GULFOILLUB,HEG,HCL-INSYS,HCLTECH,HDFCBANK,HSIL,HTMEDIA,HATHWAY,HATSUN,HAVELLS,HEIDELBERG,HERITGFOOD,HEROMOTOCO,HEXAWARE,HFCL,HSCL,HIMATSEIDE,HINDALCO,HCC,"
          + "HINDCOPPER,HINDPETRO,HINDUNILVR,HINDZINC,HONAUT,HUDCO,HDFC,HDIL,ITC,ICICIBANK,ICICIGI,ICICIPRULI,IDBI,IDFCBANK,IDFC,IFBIND,IFCI,IIFL,IL&FSTRANS,IRB,ITDCEM,"
          + "ITI,IDEA,INDIACEM,ITDC,IBULHSGFIN,IBREALEST,INDIANB,IEX,INDHOTEL,IOC,IOB,ICIL,INDOCO,IGL,INDUSINDBK,INFIBEAM,NAUKRI,INFY,INOXLEISUR,INOXWIND,"
          + "INTELLECT,INDIGO,IPCALAB,JBCHEPHARM,JKCEMENT,JKIL,JKLAKSHMI,JKTYRE,JMFINANCIL,JSWENERGY,JSWSTEEL,JAGRAN,JAICORPLTD,JISLJALEQS,"
          + "JPASSOCIAT,JPPOWER,J&KBANK,JETAIRWAYS,JINDALPOLY,JINDALSAW,JSLHISAR,JSL,JINDALSTEL,JCHAC,JUBLFOOD,JUBILANT,JUSTDIAL,JYOTHYLAB,KPRMILL,"
          + "KNRCON,KPIT,KRBL,KAJARIACER,KALPATPOWR,KANSAINER,KTKBANK,KARURVYSYA,KSCL,KEC,KESORAMIND,KITEX,KOLTEPATIL,KOTAKBANK,KWALITY,"
          + "L&TFH,LTTS,LICHSGFIN,LAXMIMACH,LAKSHVILAS,LTI,LT,LAURUSLABS,LUPIN,MASFIN,MMTC,MOIL,MRF,MAGMA,MGL,MTNL,M&MFIN,M&M,MAHINDCIE,MHRIL,"
          + "MANAPPURAM,MRPL,MANPASAND,MARICO,MARKSANS,MARUTI,MFSL,MAXINDIA,MCLEODRUSS,MERCK,MINDTREE,MINDACORP,MINDAIND,MOTHERSUMI,MOTILALOFS,"
          + "MPHASIS,MUTHOOTFIN,NATCOPHARM,NBCC,NCC,NESCO,NHPC,NIITTECH,NLCINDIA,NMDC,NTPC,NH,NATIONALUM,NFL,"
          + "NBVENTURES,NAVINFLUOR,NAVKARCORP,NETWORK18,NILKAMAL,OBEROIRLTY,ONGC,OIL,OMAXE,OFSS,ORIENTCEM,ORIENTBANK,"
          + "PCJEWELLER,PIIND,PNBHOUSING,PNCINFRA,PFS,PTC,PVR,PAGEIND,PARAGMILK,PERSISTENT,PETRONET,PFIZER,PHOENIXLTD,"
          + "PIDILITIND,PEL,PFC,POWERGRID,PRAJIND,PRESTIGE,PRSMJOHNSN,PGHH,PNB,QUESS,RBLBANK,RADICO,RAIN,RAJESHEXPO,"
          + "RALLIS,RAMCOSYS,RKFORGE,RCF,RTNPOWER,RAYMOND,REDINGTON,RELAXO,RELCAPITAL,RCOM,RHFL,RELIANCE,RELINFRA,RNAVAL,"
          + "RPOWER,RELIGARE,REPCOHOME,RUPA,RECLTD,SHK,SBILIFE,SJVN,SKFINDIA,SMLISUZU,SREINFRA,SRF,SADBHAV,SADBHIN,SANOFI,"
          + "SCHAEFFLER,SIS,SHANKARA,SFL,SCI,SHOPERSTOP,SHREECEM,RENUKA,SHRIRAMCIT,SRTRANSFIN,SIEMENS,SPTL,SOBHA,SOLARINDS,"
          + "SONATSOFTW,SOUTHBANK,STARCEMENT,SBIN,SAIL,STRTECH,SUDARSCHEM,SPARC,SUNPHARMA,SUNTV,SUNDRMFAST,SUNTECK,SUPREMEIND,"
          + "SUVEN,SUZLON,SWANENERGY,SYMPHONY,SYNDIBANK,SYNGENE,TIFIN,TTKPRESTIG,TVTODAY,TV18BRDCST,TVSMOTOR,TVSSRICHAK,TAKE,"
          + "TNPL,TATACHEM,TATACOFFEE,TATACOMM,TCS,TATAELXSI,TATAGLOBAL,TATAINVEST,TATAMTRDVR,TATAMOTORS,TATAPOWER,TATASPONGE,"
          + "TATASTEEL,TECHM,TECHNO,TEXRAIL,RAMCOCEM,THERMAX,THOMASCOOK,THYROCARE,TIMETECHNO,TIMKEN,TITAN,TORNTPHARM,TORNTPOWER,"
          + "TRENT,TRIDENT,UCOBANK,UFLEX,UPL,UJJIVAN,ULTRACEMCO,UNICHEMLAB,UNIONBANK,UNITECH,UBL,MCDOWELL-N,VGUARD,VIPIND,VRLLOG,"
          + "WABAG,VAKRANGEE,VTL,VBL,VEDL,VIJAYABANK,VINATIORGA,VOLTAS,WABCOINDIA,WELCORP,WELSPUNIND,WHIRLPOOL,WIPRO,WOCKPHARMA,FAIRCHEM,"
          + "YESBANK,ZEEL,ZEELEARN,ECLERX,ASIANTILES";

  static String allNSESymbols =
      "ZYDUSWELL,ZUARIGLOB,ZUARI,ZODJRDMKJ,ZODIACLOTH,ZICOM,ZENTEC,ZENSARTECH,ZEEMEDIA,ZEELEARN,ZEEL,YESBANK,XPROINDIA,"
      + "XCHANGING,WSTCSTPAPR,WONDERLA,WOCKPHARMA,WIPRO,WINDMACHIN,WILLAMAGOR,WHIRLPOOL,WHEELS,WENDT,WELSPUNIND,WELENT,"
      + "WELCORP,WEIZMANIND,WEIZFOREX,WEBELSOLAR,WALCHANNAG,WABCOINDIA,WABAG,VTL,VSTTILLERS,VSTIND,VSSL,VRLLOG,VOLTAS,"
      + "VOLTAMP,VMART,VLSFINANCE,VIVIMEDLAB,VISHNU,VISASTEEL,VISAKAIND,VIPULLTD,VIPIND,VIPCLOTHNG,"
      + "VINYLINDIA,VINDHYATEL,VINATIORGA,VIMTALABS,VIKASECO,VIJSHAN,VIJIFIN,VIJAYABANK,VIDHIING,VICEROY,VHL,VGUARD,VETO,"
      + "VESUVIUS,VENUSREM,VENKEYS,VEDL,VBL,VASWANI,VASCONEQ,VARDMNPOLY,VARDHACRLC,VAKRANGEE,VAIBHAVGBL,VADILALIND,V2RETAIL,"
      + "UTTAMSUGAR,UTTAMSTL,USHERAGRO,USHAMART,URJA,UPL,UNIVCABLES,UNITY,UNITEDTEA,UNITEDBNK,"
      + "UNITECH,UNIPLY,UNIONBANK,UNIENTER,UNICHEMLAB,UMANGDAIRY,ULTRACEMCO,UJJIVAN,UJAAS,UGARSUGAR,UFO,UFLEX,UCOBANK,UCALFUEL,"
      + "UBL,TWL,TVVISION,TVTODAY,TVSSRICHAK,TVSMOTOR,TV18BRDCST,TTL,TTKPRESTIG,TTKHLTCARE,TRIVENI,TRITURBINE,TRIL,TRIGYN,"
      + "TRIDENT,TRF,TRENT,TREEHOUSE,TPLPLASTEH,TORNTPOWER,TORNTPHARM,TOKYOPLAST,TNPL,TNPETRO,TMRVL,TITAN,TIRUMALCHM,TIPSINDLTD,"
      + "TINPLATE,TIMKEN,TIMETECHNO,TIMESGTY,TIL,TIINDIA,TIIL,TIFIN,TIDEWATER,TI,THYROCARE,THOMASCOOK,THIRUSUGAR,THERMAX,THEMISMED,"
      + "THANGAMAYL,TGBHOTELS,TFCILTD,TEXRAIL,TEXMOPIPES,TEXINFRA,TEJASNET,TECHNOFAB,TECHNO,TECHM,TEAMLEASE,TDPOWERSYS,TCS,TCPLPACK,"
      + "TCIFINANCE,TCIEXP,TCI,TBZ,TATASTEEL,TATASPONGE,TATAPOWER,TATAMTRDVR,TATAMOTORS,TATAMETALI,TATAINVEST,TATAGLOBAL,"
      + "TATAELXSI,TATACOMM,TATACOFFEE,TATACHEM,TASTYBITE,TARMAT,TARAJEWELS,TALWALKARS,TALBROAUTO,TAKE,TAJGVK,SYNGENE,SYNDIBANK,SYNCOM,"
      + "SYMPHONY,SWELECTES,SWARAJENG,SWANENERGY,SUZLON,SUVEN,SUTLEJTEX,SURYAROSNI,SURYALAXMI,SURANAT&P,SURANASOL,SUPREMEINF,"
      + "SUPREMEIND,SUPRAJIT,SUPPETRO,SUPERHOUSE,SUNTV,SUNTECK,SUNPHARMA,SUNILHITEC,SUNFLAG,SUNDRMFAST,SUNDRMBRAK,SUNDARMFIN,"
      + "SUNDARAM,SUNCLAYLTD,SUMMITSEC,SUMEETINDS,SUDARSCHEM,SUBROS,SUBEX,STRTECH,STINDIA,STERTOOLS,STEL,STEELXIND,STCINDIA,"
      + "STARPAPER,STARCEMENT,STAR,STAMPEDE,SSWL,SRTRANSFIN,SRIPIPES,SRHHYPOLTD,SRF,SREINFRA,SREEL,SQSBFSI,SPTL,SPMLINFRA,SPLIL,"
      + "SPICEMOBI,SPIC,SPENTEX,SPECIALITY,SPARC,SPAL,SOUTHBANK,SOTL,SONATSOFTW,SOMICONVEY,SOMANYCERA,SOLARINDS,SOBHA,SNOWMAN,"
      + "SMSPHARMA,SMSLIFE,SMLISUZU,SMARTLINK,SKMEGGPROD,SKIPPER,SKIL,SKFINDIA,SJVN,SIYSIL,SITINET,SIS,SINTEX,SIMPLEXINF,SIMPLEX,"
      + "SIMBHALS,SILINV,SIGNET,SIEMENS,SICAL,SICAGEN,SHYAMTEL,SHRIRAMEPC,SHRIRAMCIT,SHREYAS,SHREYANIND,SHREERAMA,SHREEPUSHK,"
      + "SHREECEM,SHOPERSTOP,SHK,SHIVATEX,SHIVAMILLS,SHIVAMAUTO,SHIRPUR-G,SHILPAMED,SHEMAROO,SHARDAMOTR,SHARDACROP,"
      + "SHANTIGEAR,SHANKARA,SHALPAINTS,SHALBY,SHAKTIPUMP,SHAHALLOYS,SGL,SFL,SETCO,"
      + "SESHAPAPER,SEQUENT,SEPOWER,SELMCL,SELAN,SEAMECLTD,SDBL,SCI,SCHNEIDER,SCHAND,SCHAEFFLER,SBIN,SBILIFE,SATIN,SATHAISPAT,"
      + "SASTASUNDR,SASKEN,SARLAPOLY,SAREGAMA,SARDAEN,SANWARIA,SANOFI,SANGHVIMOV,SANGHVIFOR,SANGHIIND,SANGAMIND,SANDHAR,"
      + "SANDESH,SANCO,SAMBHAAV,SALZERELEC,SALSTEEL,SALORAINTL,SALONA,SALASAR,SAKUMA,SAKSOFT,SAKHTISUG,SAIL,SAGCEM,SADBHIN,"
      + "SADBHAV,SABTN,SABEVENTS,RUSHIL,RUPA,RUCHISOYA,RUCHIRA,RUBYMILLS,RTNPOWER,RTNINFRA,RSYSTEMS,RSWM,RSSOFTWARE,"
      + "RPPINFRA,RPOWER,RPGLIFE,ROSSELLIND,ROLTA,ROLLT,ROHLTD,ROHITFERRO,RNAVAL,RNAM,RML,RMCL,RKFORGE,RKDL,RJL,RIIL,RICOAUTO,"
      + "RHFL,REVATHI,RESPONIND,REPRO,REPCOHOME,RENUKA,REMSONSIND,RELINFRA,RELIGARE,RELIANCE,RELDIVOPP,RELCAPITAL,"
      + "RELAXO,REFEX,REDINGTON,RECLTD,RCOM,RCF,RBLBANK,RBL,RAYMOND,RATNAMANI,RANEHOLDIN,RANEENGINE,RANASUG,RAMKY,RAMCOSYS,"
      + "RAMCOIND,RAMCOCEM,RAMASTEEL,RAMANEWS,RALLIS,RAJTV,RAJSREESUG,RAJESHEXPO,RAINBOWPAP,RAIN,RADIOCITY,RADICO,QUICKHEAL,"
      + "QUESS,QGOLDHALF,PVR,PVP,PURVA,PUNJABCHEM,PTL,PTC,PSPPROJECT,PSL,PSB,PRSMJOHNSN,PROZONINTU,"
      + "PROVOGE,PRIMESECU,PRICOLLTD,PRESTIGE,PRESSMN,PREMIERPOL,PREMIER,PREMEXPLN,PRECWIRE,PRECOT,PRECAM,PRAKASHCON,PRAKASH,"
      + "PRAJIND,PRAENG,PRABHAT,PPAP,POWERMECH,POWERGRID,PONNIERODE,POLYPLEX,POLYMED,POLARIS,POKARNA,PODDARMENT,PODDARHOUS,"
      + "POCHIRAJU,PNCINFRA,PNC,PNBHOUSING,PNBGILTS,PNB,PLASTIBLEN,PITTIENG,PIONEEREMB,PIONDIST,PILITA,PIIND,PIDILITIND,"
      + "PHOENIXLTD,PHILIPCARB,PGIL,PGHH,PGEL,PFS,PFOCUS,PFIZER,PFC,PETRONET,PERSISTENT,PENPEBS,PENINLAND,PENIND,PEL,PEARLPOLY,"
      + "PDSMFL,PDPL,PDMJEPAPER,PCJEWELLER,PBAINFRA,PATSPINLTD,PATINTLOG,PATELENG,PARSVNATH,PARAGMILK,PARACABLES,PAPERPROD,"
      + "PANAMAPET,PANACEABIO,PALREDTEC,PALASHSECU,PAISALO,PAGEIND,OSWALAGRO,ORTINLABSS,ORTEL,ORISSAMINE,ORIENTREF,ORIENTPPR,"
      + "ORIENTLTD,ORIENTHOT,ORIENTELEC,ORIENTCEM,ORIENTBELL,ORIENTBANK,ORIENTALTL,ORIENTABRA,ORICONENT,ORBTEXP,OPTOCIRCUI,"
      + "OPTIEMUS,ONWARDTEC,ONMOBILE,ONGC,OMMETALS,OMKARCHEM,OMAXE,OISL,OILCOUNTUB,OIL,OFSS,OCL,OCCL,OBEROIRLTY,NUCLEUS,"
      + "NTPC,NSIL,NRBBEARING,NRAIL,NORBTEAEXP,NOIDATOLL,NOCIL,NMDC,NLCINDIA,NKIND,NITINSPIN,NITESHEST,NITCO,NIPPOBATRY,NILKAMAL,"
      + "NILAINFRA,NIITTECH,NIITLTD,NIBL,NIACL,NHPC,NH,NFL,NEWGEN,NEULANDLAB,NETWORK18,NESTLEIND,NESCO,NELCAST,"
      + "NECLIFE,NECCLTD,NDTV,NDL,NDGL,NCLIND,NCC,NBVENTURES,NBCC,NAVNETEDUL,NAVKARCORP,NAVINFLUOR,NAUKRI,NATNLSTEEL,"
      + "NATIONALUM,NATHBIOGEN,NATCOPHARM,NAHARSPING,NAHARPOLY,NAHARINDUS,NAHARCAP,NAGREEKEXP,NAGREEKCAP,NAGAROIL,NAGAFERT,"
      + "NACLIND,MUTHOOTFIN,MUTHOOTCAP,MURUDCERA,MUNJALSHOW,MUNJALAU,MUKTAARTS,MUKANDLTD,MUKANDENGG,MTNL,MTEDUCARE,MSPL,"
      + "MRPL,MRO-TEK,MRF,MPSLTD,MPHASIS,MOTOGENFIN,MOTILALOFS,MOTHERSUMI,MOREPENLAB,MORARJEE,MONTECARLO,MONSANTO,MOLDTKPAC,"
      + "MOLDTECH,MOIL,MOHOTAIND,MOHITIND,MMTC,MMFL,MIRZAINT,MIRCELECTR,MINDTREE,MINDAIND,MINDACORP,MIDHANI,MHRIL,MGL,MFSL,"
      + "METKORE,METALFORGE,MERCK,MERCATOR,MEP,MENONBE,MEGH,MEGASOFT,MCX,MCLEODRUSS,MCDOWELL-N,MCDHOLDING,MBLINFRA,MAZDA,"
      + "MAYURUNIQ,MAXVIL,MAXINDIA,MAWANASUG,MATRIMONY,MASTEK,MASFIN,MARUTI,MARKSANS,MARICO,MARATHON,MARALOVER,MANUGRAPH,"
      + "MANPASAND,MANINFRA,MANINDS,MANGTIMBER,MANGLMCEM,MANGCHEFER,MANGALAM,MANAPPURAM,MANALIPETC,MANAKSTEEL,MANAKSIA,MANAKCOAT,"
      + "MANAKALUCO,MAJESCO,MAITHANALL,MAHSEAMLES,MAHSCOOTER,MAHLOG,MAHLIFE,MAHINDCIE,MAHABANK,MAGNUM,MAGMA,MAGADSUGAR,MADRASFERT,"
      + "MADHUCON,MADHAV,MAANALU,M&MFIN,M&M,LYPSAGEMS,LYKALABS,LUXIND,LUPIN,LUMAXTECH,LUMAXIND,LTTS,LTI,LT,LPDC,"
      + "LOVABLE,LOTUSEYE,LOKESHMACH,LINDEINDIA,LINCOLN,LICHSGFIN,"
      + "LIBERTSHOE,LGBBROSLTD,LEMONTREE,LEEL,LAXMIMACH,LAURUSLABS,LASA,LAOPALA,LAMBODHARA,LALPATHLAB,LAKSHVILAS,LAKSHMIEFL,LAKPRE"
      + ",L&TFH,KWALITY,KTKBANK,KTIL,KSL,KSK,KSCL,KSBPUMPS,KRIDHANINF,KRBL,KPRMILL,KPIT,KOTHARIPRO,KOTHARIPET,KOTARISUG,"
      + "KOTAKBANK,KOPRAN,KOLTEPATIL,KOKUYOCMLN,KOHINOOR,KNRCON,KMSUGAR,KKCL,KITEX,KIRLOSIND,KIRLOSENG,KIRLOSBROS,KIRIINDUS,KIOCL,"
      + "KINGFA,KILITCH,KICL,KHAITANLTD,KHADIM,KESORAMIND,KESARENT,KELLTONTEC,KEI,KECL,KEC,KDDL,KCPSUGIND,KCP,"
      + "KAYA,KAVVERITEL,KAUSHALYA,KARURVYSYA,KARMAENG,KARDA,KANSAINER,KANORICHEM,KANANIIND,KAMDHENU,KAMATHOTEL,KALPATPOWR,"
      + "KAKATCEM,KAJARIACER,KABRAEXTRU,JYOTHYLAB,JVLAGRO,JUSTDIAL,JUBLINDS,JUBLFOOD,JUBILANT,JTEKTINDIA,JSWSTEEL,"
      + "JSWHL,JSWENERGY,JSLHISAR,JSL,JPPOWER,JPOLYINVST,JPASSOCIAT,JOCIL,JMFINANCIL,JMCPROJECT,JMA,JKTYRE,JKPAPER,"
      + "JKLAKSHMI,JKIL,JKCEMENT,JISLJALEQS,JISLDVREQS,JINDWORLD,JINDRILL,JINDALSTEL,JINDALSAW,JINDALPOLY,JINDALPHOT,JHS,"
      + "JETAIRWAYS,JCHAC,JBMA,JBCHEPHARM,JAYSREETEA,JAYNECOIND,JAYBARMARU,JAYAGROGN,JAMNAAUTO,JAICORPLTD,JAIBALAJI,JAGSNPHARM,"
      + "JAGRAN,J&KBANK,IZMO,IVRCLINFRA,IVP,IVC,ITI,ITDCEM,ITDC,ITC,ISMTLTD,ISFT,ISEC,IRB,IPCALAB,IPAPPM,IOC,IOB,"
      + "INVENTURE,INTENTECH,INTELLECT,INSECTICID,INOXWIND,INOXLEISUR,INGERRAND,INFY,INFRATEL,INFINITE,INFIBEAM,INEOSSTYRO,"
      + "INDUSINDBK,INDTERRAIN,INDSWFTLAB,INDRAMEDCO,INDOWIND,INDOTHAI,INDOTECH,INDOSTAR,INDOSOLAR,INDORAMA,INDOCO,INDNIPPON,"
      + "INDLMETER,INDIGO,INDIANHUME,INDIANCARD,INDIANB,INDIAGLYCO,INDIACEM,INDHOTEL,INDBANK,IMPAL,IMFA,IL&FSTRANS,IL&FSENGG,"
      + "IIFL,IGPL,IGL,IGARASHI,IFGLEXPOR,IFCI,IFBIND,IEX,IDFCBANK,IDFC,IDEA,IDBI,ICRA,ICIL,"
      + "ICICIPRULI,ICICIGI,ICICIBANK,IBULHSGFIN,"
      + "IBREALEST,HUDCO,HUBTOWN,HTMEDIA,HSIL,HSCL,HPL,HOVS,HOTELEELA,HONDAPOWER,HONAUT,HMVL,HITECHGEAR,HITECHCORP,HITECH,"
      + "HISARMETAL,HIRECT,HINDZINC,HINDUNILVR,HINDUJAVEN,HINDSYNTEX,HINDPETRO,HINDOILEXP,HINDNATGLS,HINDMOTORS,HINDCOPPER,HINDCOMPOS,"
      + "HINDALCO,HIMATSEIDE,HIL,HIKAL,HIGHGROUND,HGS,HGINFRA,HFCL,HEXAWARE,HESTERBIO,HEROMOTOCO,HERITGFOOD,HERCULES,HEIDELBERG,HEG,"
      + "HDIL,HDFCLIFE,HDFCBANK,HDFC,HCLTECH,HCL-INSYS,HCG,HCC,HBLPOWER,HAVELLS,HATSUN,HATHWAY,HARRMALAYA,"
      + "HARITASEAT,HAL,GVKPIL,GULPOLY,GULFPETRO,GULFOILLUB,GUJGASLTD,GUJFLUORO,GUJAPOLLO,GUJALKALI,GUFICBIO,GTPL,GTNTEX,GTNIND,GTL,"
      + "GSS,GSPL,GSKCONS,GSFC,GSCLCEMENT,GRUH,GRPLTD,GRINDWELL,GREENPOWER,GREENPLY,GREENLAM,GREAVESCOT,GRAVITA,GRASIM,GRAPHITE,"
      + "GRANULES,GPTINFRA,GPPL,GPIL,GOODLUCK,GOLDTECH,GOLDINFRA,GOLDIAM,GOKULAGRO,GOKUL,GOKEX,GODREJPROP,"
      + "GODREJIND,GODREJCP,GODREJAGRO,GODFRYPHLP,GOCLCORP,GOACARBON,GNFC,GNA,GMRINFRA,GMMPFAUDLR,GMDCLTD,GMBREW,GLOBUSSPR,GLOBALVECT,"
      + "GLENMARK,GLAXO,GIPCL,GINNIFILA,GILLETTE,GILLANDERS,GICRE,GICHSGFIN,GHCL,GET&D,GESHIP,GEPIL,GEOJITFSL,GENUSPOWER,GENUSPAPER,"
      + "GENESYS,GEECEE,GDL,GAYAPROJ,GATI,GARWALLROP,GARDENSILK,GANGESSECU,GANESHHOUC,GANECOS,GANDHITUBE,GAMMNINFRA,GALLISPAT,GALLANTT,"
      + "GALAXYSURF,GAL,GAIL,GAEL,GABRIEL,FSL,FSC,FRETAIL,FOSECOIND,FORTUNEFIN,FORTIS,FMNL,FMGOETZE,FLFL,FLEXITUFF,FINPIPE,FINCABLES,"
      + "FILATEX,FIEMIND,FELDVR,FEL,FEDERALBNK,FEDDERELEC,FDC,FCONSUMER,FCL,FAIRCHEM,FACT,EXIDEIND,EXCELINDUS,EXCELCROP,EXCEL,EVERESTIND,"
      + "EVEREADY,EUROTEXIND,ESTER,ESSELPACK,ESSARSHPNG,ESCORTS,ESABINDIA,EROSMEDIA,ERIS,EQUITAS,EON,ENIL,ENGINERSIN,ENERGYDEV,"
      + "ENDURANCE,EMMBI,EMKAY,EMAMILTD,EMAMIINFRA,ELGIRUBCO,ELGIEQUIP,ELECTHERM,ELECTCAST,ELECON,ELAND,EKC,EIMCOELECO,EIHOTEL,EIHAHOTELS"
      + ",EIDPARRY,EICHERMOT,EDL,EDELWEISS,ECLERX,ECEIND,EASTSILK,DYNPRO,DYNAMATECH,DWARKESH,DUCON,DTIL,DSSL,DRREDDY,DREDGECORP,"
      + "DPSCLTD,DPL,DONEAR,DOLPHINOFF,DOLLAR,DNAMEDIA,DMART,DLF,DIXON,DIVISLAB,DISHTV,DIGJAMLTD,DICIND,DIAMONDYD,DHUNINV,DHFL,DHANUKA,"
      + "DHANBANK,DHAMPURSUG,DFMFOODS,DENORA,DENABANK,DEN,DELTACORP,DEEPIND,DEEPAKNTR,DEEPAKFERT,DECCANCE,DCW,DCMSHRIRAM,"
      + "DCM,DCBBANK,DCAL,DBREALTY,DBL,DBCORP,DATAMATICS,DAMODARIND,DALMIASUG,DALMIABHA,DABUR,DAAWAT,CYIENT,CYBERTECH,"
      + "CUPID,CUMMINSIND,CUB,CTE,CROMPTON,CRISIL,CREST,COX&KINGS,COUNCODOS,COSMOFILMS,CORPBANK,COROMANDEL,CORDSCABLE,CORALFINAC,"
      + "CONTROLPR,CONSOFINVT,CONCOR,COMPUSOFT,COMPINFO,COLPAL,COFFEEDAY,COCHINSHIP,COALINDIA,CNOVAPETRO,CMICABLES,CLNINDIA,CLEDUCATE,"
      + "CIPLA,CINEVISTA,CINELINE,CIMMCO,CIGNITITEC,CHOLAFIN,CHENNPETRO,CHAMBLFERT,CGPOWER,CGCL,CESC,CERA,CENTURYTEX,CENTURYPLY,"
      + "CENTUM,CENTRUM,CENTRALBK,CENTEXT,CENTENKA,CELESTIAL,CELEBRITY,CEBBCO,CEATLTD,CDSL,CCL,CCHHL,CCCL,CASTROLIND,CARERATING,CAREERP,"
      + "CARBORUNIV,CAPTRUST,CAPLIPOINT,CAPF,CAPACITE,CANFINHOME,CANDC,CANBK,CAMLINFINE,CADILAHC,BYKE,BUTTERFLY,BSL,"
      + "BSELINFRA,BSE,BROOKS,BRNL,BRITANNIA,BRIGADE,BPL,BPCL,BOSCHLTD,BOROSIL,BOMDYEING,BODALCHEM,BLUESTARCO,BLUEDART,BLUEBLENDS,BLS,"
      + "BLKASHYAP,BLISSGVS,BKMINDST,BIRLACORPN,BIOCON,BINDALAGRO,BINANIIND,BIL,BIGBLOC,BHUSANSTL,BHEL,BHARTIARTL,BHARATWIRE,BHARATRAS,"
      + "BHARATGEAR,BHARATFORG,BHARATFIN,BHANDARI,BHAGYANGR,BHAGERIA,BGRENERGY,BFUTILITIE,BFINVEST,BERGEPAINT,BEPL,BEML,BEL,BEARDSELL,"
      + "BDL,BBTC,BBL,BAYERCROP,BATAINDIA,BASML,BASF,BANSWRAS,BANKINDIA,BANKBARODA,BANG,BANDHANBNK,BANCOINDIA,BANARISUG,"
      + "BANARBEADS,BALRAMCHIN,BALPHARMA,BALMLAWRIE,BALLARPUR,BALKRISIND,BALKRISHNA,BALAMINES,BALAJITELE,BAJFINANCE,BAJAJHLDNG,"
      + "BAJAJHIND,BAJAJFINSV,BAJAJELEC,BAJAJCORP,BAJAJ-AUTO,BAGFILMS,BAFNAPHARM,AYMSYNTEX,AXISCADES,AXISBANK,"
      + "AVTNPL,AVANTIFEED,AVADHSUGAR,AUTOLITIND,AUTOIND,AUTOAXLES,AUSOMENT,AUROPHARMA,AURIONPRO,AUBANK,ATULAUTO,ATUL,ATLANTA,"
      + "ATFL,ASTRON,ASTRAZEN,ASTRAMICRO,ASTRAL,ASTERDM,ASTEC,ASSAMCO,ASPINWALL,ASIANTILES,ASIANPAINT,ASIANHOTNR,ASHOKLEY,ASHOKA,"
      + "ASHIMASYN,ASHIANA,ASHAPURMIN,ASAL,ASAHISONG,ASAHIINDIA,ARVSMART,ARVIND,ARSHIYA,ARROWTEX,ARROWGREEN,AROGRANITE,ARIHANTSUP,"
      + "ARIES,ARCOTECH,ARCHIDPLY,APTECHT,APOLSINHOT,APOLLOTYRE,APOLLOHOSP,APOLLO,APLLTD,APLAPOLLO,APEX,APCOTEXIND,APCL,"
      + "APARINDS,ANSALHSG,ANSALAPI,ANDHRSUGAR,ANDHRACEMT,ANDHRABANK,ANANTRAJ,AMRUTANJAN,AMJLAND,AMDIND,AMBUJACEM,AMBIKCO,AMBER,"
      + "AMARAJABAT,ALPHAGEO,ALPA,ALLSEC,ALLCARGO,ALKYLAMINE,ALKEM,ALKALI,ALICON,ALEMBICLTD,ALBK,ALBERTDAVD,ALANKIT,AKZOINDIA,"
      + "AKSHOPTFBR,AKSHARCHEM,AJMERA,AJANTPHARM,AIFL,AIAENG,AHLUCONT,AHLEAST,AGRITECH,AGLSL,AGCNET,AGARIND,AFL,AEGISCHEM,ADVENZYMES,"
      + "ADVANIHOTR,ADSL,ADROITINFO,ADORWELD,ADLABS,ADHUNIKIND,ADHUNIK,ADFFOODS,ADANITRANS,ADANIPOWER,ADANIPORTS,ADANIENT,ACE,ACCELYA,"
      + "ACC,ABFRL,ABCAPITAL,ABBOTINDIA,ABB,ABAN,AARVEEDEN,AARTIIND,AARTIDRUGS,A2ZINFRA,8KMILES,63MOONS,5PAISA,3PLAND,3MINDIA,3IINFOTECH,21STCENMGM,20MICRONS";


  String nseInError = "TCIDEVELOP,NBIFIN,LINCPEN,LICNETFSEN,KHANDSE,IVZINGOLD,IITL,IDFNIFTYET,EBANK,DCMFINSERV,DELTAMAGNT,CYBERMEDIA,ARIHANT,";
  
  String mySmallCap = "";

  // BAJAJ-AUTO
  public static List<String> getSymbols() {
    List<String> l = new ArrayList<String>();
    StringTokenizer s1 = new StringTokenizer(allNSESymbols, ",");
    while (s1.hasMoreTokens()) {
      l.add(s1.nextToken());
    }

    return l;
  }

  public static Set<String> getTopSelectedSymbols() {
    Set<String> l = new HashSet<String>();
    StringTokenizer s1 = new StringTokenizer(selectedTopSheet, ",");
    while (s1.hasMoreTokens()) {
      l.add(s1.nextToken());
    }

    return l;
  }

  public static Set<String> getBadStocksSymbols() {
    Set<String> l = new HashSet<String>();
    StringTokenizer s1 = new StringTokenizer(badList, ",");
    while (s1.hasMoreTokens()) {
      l.add(s1.nextToken());
    }

    return l;
  }

  public List<String> getHoldingSymbols() {
    List<String> l = new ArrayList<String>();
    StringTokenizer s1 = new StringTokenizer(holdings, ",");
    while (s1.hasMoreTokens()) {
      l.add(s1.nextToken());
    }

    return l;
  }
}


